server:
  port: 8080
spring:
  jpa:
    show-sql: true
    database: h2
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create
  datasource:
    driver-class-name: org.h2.Driver
    embedded-database-connection: h2
    url: jdbc:h2:mem:testdb
    username: mike
    password: mike